### ISSUE TITLE
GPU Error when running the test examples

### ISSUE THREAD

**Issue by pavanyogi** [fyviezhao/M3D-VTON#17]
We are getting graphic card related error. 
Here are my system info 
```bash
pavan@u-20:~/.../M3D-VTON$ sudo dmidecode -t 1
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.

Handle 0x000C, DMI type 1, 27 bytes
System Information
	Manufacturer: LENOVO
	Product Name: 20JUS05X00
	Version: ThinkPad L470 W10DG
	Serial Number: PF11SM82
	UUID: 31f6b94c-2fd0-11b2-a85c-ed0533b508ea
	Wake-up Type: Power Switch
	SKU Number: LENOVO_MT_20JU_BU_Think_FM_ThinkPad L470 W10DG
	Family: ThinkPad L470 W10DG

pavan@u-20:~/.../M3D-VTON$
pavan@u-20:~/.../M3D-VTON$ inxi -G
Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.13 driver: i915 resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 21.2.6 
pavan@u-20:~/.../M3D-VTON$ 

pavan@u-20:~/.../M3D-VTON$ python3 test.py --model MTM --name MTM --dataroot mpv3d_example --datalist test_pairs --results_dir results
                  verbose: False                         
----------------- End -------------------
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    opt = TestOptions().parse()  # get test options
  File "/home/pavan/Documents/aux/tmp-git/virtual-try-on/M3D-VTON/options/base_options.py", line 130, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/home/pavan/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/pavan/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
pavan@u-20:~/.../M3D-VTON$
```

is it possible to run it on my machine? I have attached my machine info also.

**Comment by fyviezhao** [comment]
I have checked the information of ThinkPad L470 laptop and looks like it has no NVIDIA GPU support. Therefore it is nearly impossible to run M3D-VTON on this machine. A computer or server with NVIDIA GPU support is strongly preferred for running the code.
